### ISSUE TITLE
How to obtain the groundtruth boundary for ADE20K dataset?

### ISSUE THREAD

**Issue by whuhxb** [wangchi95/active-boundary-loss#4]
Hi @wangchi95 ;

As we know, ADE20K dataset is for semantic segmentation. How to obtain the labeled groundtruth boundary?

Thanks.

**Comment by wangchi95** [comment]
Hello whuhxb,

Since we have semantic segmentation annotations, the semantic boundary labels can be obtained by compasring each pixel individually for equality with surrounding pixels (2-neighborhood in the implementation). For more details, you can refer to the **_Phase I_** chapter in our paper and the following code: https://github.com/wangchi95/active-boundary-loss/blob/958218d2d677ac9970d3e949049a672461d3c3de/abl.py#L89

**Comment by whuhxb** [comment]
@wangchi95 
Thanks a lot.
